// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.1";

// src/lib/mcp/tools/get-portfolio.ts
import { createClient } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.1";
function sbForUser(ctx) {
  return createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_portfolio_default = defineTool({
  name: "get_portfolio",
  title: "Get portfolio",
  description: "Get the signed-in user's paper trading account balance, equity, and open positions.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser(ctx);
    const userId = ctx.getUserId();
    const [{ data: account }, { data: positions }] = await Promise.all([
      sb.from("paper_account").select("*").eq("user_id", userId).maybeSingle(),
      sb.from("paper_positions").select("*").eq("user_id", userId)
    ]);
    const payload = { account, positions: positions ?? [] };
    return {
      content: [{ type: "text", text: JSON.stringify(payload, null, 2) }],
      structuredContent: payload
    };
  }
});

// src/lib/mcp/tools/get-recent-trades.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z } from "npm:zod@^3.25.76";
function sbForUser2(ctx) {
  return createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_recent_trades_default = defineTool2({
  name: "get_recent_trades",
  title: "Get recent trades",
  description: "Return the signed-in user's most recent trades, newest first.",
  inputSchema: {
    limit: z.number().int().min(1).max(100).default(20).describe("Max number of trades to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser2(ctx);
    const { data, error } = await sb.from("trades").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(limit);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { trades: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/get-bot-status.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.1";
function sbForUser3(ctx) {
  return createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var get_bot_status_default = defineTool3({
  name: "get_bot_status",
  title: "Get bot status",
  description: "Get the AI trading bot settings for the signed-in user, including enabled state, kill switch, and risk settings.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser3(ctx);
    const { data, error } = await sb.from("ai_settings").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data, null, 2) }],
      structuredContent: { settings: data }
    };
  }
});

// src/lib/mcp/tools/set-bot-enabled.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.86.2";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.1";
import { z as z2 } from "npm:zod@^3.25.76";
function sbForUser4(ctx) {
  return createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
    global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}
var set_bot_enabled_default = defineTool4({
  name: "set_bot_enabled",
  title: "Start or stop trading bot",
  description: "Enable or disable the AI trading bot for the signed-in user. Set enabled=true to start, false to stop.",
  inputSchema: {
    enabled: z2.boolean().describe("true to start the bot, false to stop it.")
  },
  annotations: { readOnlyHint: false, destructiveHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ enabled }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const sb = sbForUser4(ctx);
    const patch = {
      enabled,
      updated_at: (/* @__PURE__ */ new Date()).toISOString()
    };
    if (enabled) {
      patch.kill_switch_active = false;
      patch.kill_switch_triggered_at = null;
      patch.bot_status = "idle";
    } else {
      patch.bot_status = "idle";
    }
    const { data, error } = await sb.from("ai_settings").update(patch).eq("user_id", ctx.getUserId()).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Bot ${enabled ? "started" : "stopped"}.` }],
      structuredContent: { settings: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "obtfgoktgigulszrfzvp";
var mcp_default = defineMcp({
  name: "titanai-mcp",
  title: "TitanAI Trading MCP",
  version: "0.1.0",
  instructions: "Tools for the TitanAI trading app. Use get_portfolio, get_recent_trades, and get_bot_status to inspect the signed-in user's paper trading account and AI bot. Use set_bot_enabled to start or stop the bot (requires approval).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_portfolio_default, get_recent_trades_default, get_bot_status_default, set_bot_enabled_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
